

services:
  # 1. Хранилище (MinIO)
  minio:
    image: minio/minio:latest
    container_name: cloud_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Бэкенд (FastAPI)
  backend:
    build: ./backend
    container_name: cloud_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Используем сложный depends_on только там, где критична проверка здоровья (MinIO)
    depends_on:
      minio:
        condition: service_healthy
    
  # 3. Фронтенд (Streamlit)
  frontend:
    build: ./frontend
    container_name: cloud_frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    # Используем простой список для зависимостей, чтобы избежать ошибки must be a string
    depends_on:
      - backend 
      
volumes:
  minio_data: